# Generated by Django 5.2.5 on 2025-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronkz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='ankara', unique=True),
            preserve_default=False,
        ),
    ]
