# Generated by Django 5.2.5 on 2025-08-21 13:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronkz', '0003_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('style_description', models.TextField()),
                ('occasion', models.CharField(choices=[('birthday', 'Birthday'), ('burial', 'Burial'), ('graduation', 'Graduation'), ('office', 'Office'), ('wedding', 'Wedding')], max_length=20)),
                ('budget', models.CharField(choices=[('15000-25000', '₦15,000 - ₦25,000'), ('25000-30000', '₦25,000 - ₦30,000'), ('30000-40000', '₦30,000 - ₦40,000'), ('40000-50000', '₦40,000 - ₦50,000'), ('50000+', '₦50,000 +')], max_length=20)),
                ('timeline', models.DateField()),
                ('style_image', models.ImageField(blank=True, null=True, upload_to='custom_orders/styles/')),
                ('personal_image', models.ImageField(blank=True, null=True, upload_to='custom_orders/personal/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Order',
                'verbose_name_plural': 'Custom Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bust_chest', models.DecimalField(decimal_places=2, help_text='Bust/Chest measurement in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('waist', models.DecimalField(decimal_places=2, help_text='Waist measurement in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('hips', models.DecimalField(decimal_places=2, help_text='Hips measurement in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(36), django.core.validators.MaxValueValidator(84)])),
                ('inseam', models.DecimalField(decimal_places=2, help_text='Inseam measurement in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)])),
                ('neck', models.DecimalField(decimal_places=2, help_text='Neck measurement in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(25)])),
                ('arms', models.DecimalField(decimal_places=2, help_text='Arm length in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(40)])),
                ('shoulders', models.DecimalField(decimal_places=2, help_text='Shoulder width in inches', max_digits=5, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(30)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='ronkz.customorder')),
            ],
            options={
                'verbose_name': 'Customer Measurement',
                'verbose_name_plural': 'Customer Measurements',
            },
        ),
        migrations.CreateModel(
            name='CustomOrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ronkz.customorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
