# Generated by Django 5.2.5 on 2025-08-29 15:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronkz', '0004_customorder_customermeasurement_customordernote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customordernote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customordernote',
            name='custom_order',
        ),
        migrations.RenameField(
            model_name='customorder',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customorder',
            old_name='style_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='customorder',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='customorder',
            old_name='personal_image',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='customorder',
            old_name='style_description',
            new_name='styleDescription',
        ),
        migrations.RenameField(
            model_name='customorder',
            old_name='whatsapp_number',
            new_name='whatsapp',
        ),
        migrations.AddField(
            model_name='customorder',
            name='arms',
            field=models.FloatField(default=11, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customorder',
            name='chest',
            field=models.FloatField(default=34, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customorder',
            name='height',
            field=models.FloatField(default=60, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customorder',
            name='hips',
            field=models.FloatField(default=36, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customorder',
            name='inseam',
            field=models.FloatField(default=32, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customorder',
            name='neck',
            field=models.FloatField(default=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customorder',
            name='shoulders',
            field=models.FloatField(default=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customorder',
            name='waist',
            field=models.FloatField(default=28, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='CustomOrderCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_carts', to='ronkz.customorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerMeasurement',
        ),
        migrations.DeleteModel(
            name='CustomOrderNote',
        ),
    ]
