# Generated by Django 5.2.5 on 2025-08-29 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronkz', '0005_remove_customordernote_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='budget',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='occasion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customordercart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_order_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
