# Generated by Django 5.2.5 on 2025-08-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronkz', '0006_alter_customorder_budget_alter_customorder_occasion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customordercart',
            name='customorder',
        ),
        migrations.RemoveField(
            model_name='customordercart',
            name='user',
        ),
        migrations.CreateModel(
            name='CustomOrderCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ronkz.customordercart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ronkz.customorder')),
            ],
        ),
    ]
