# Generated by Django 5.2.5 on 2025-08-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronkz', '0007_remove_customordercart_customorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customorder',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customorder',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
