# Generated by Django 5.2.5 on 2025-08-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
