# Generated by Django 5.2.5 on 2025-08-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_email_validated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_email_validated',
            new_name='is_email_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
